FROM mxe/mxe:latest AS builder

# The image already has the toolchain and libraries.
# We only need to build our project.

WORKDIR /app
COPY . /app

# Build with the MXE toolchain
RUN mkdir build && cd build && \
    cmake .. \
    -DCMAKE_TOOLCHAIN_FILE=/usr/share/mxe/toolchain.cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_FLAGS="-static-libgcc -static-libstdc++" && \
    make -j$(nproc)

CMD cp /app/build/3dco.exe /dist/windows/