FROM mxe/mxe:latest AS builder

WORKDIR /app
COPY . /app

# Build with the MXE toolchain
RUN mkdir build && cd build && \
    cmake .. \
    -DCMAKE_TOOLCHAIN_FILE=/usr/share/mxe/toolchain.cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_FLAGS="-static-libgcc -static-libstdc++" && \
    make -j$(nproc)


CMD mkdir -p /dist/windows && \
    cp /app/build/3dco+.exe /dist/windows/ && \
    cp -r /app/assets/models /dist/windows/models
